// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using DocumentDBRestApi.Models;
using Microsoft.Rest;

namespace DocumentDBRestApi
{
    /// <summary>
    /// 
    /// </summary>
    public interface IDocumentDbConnector : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri
        {
            get; set;
        }

        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        ServiceClientCredentials Credentials
        {
            get; set;
        }

        /// <summary>
        /// Create an Attachment
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection Id
        /// </param>
        /// <param name='ridDoc'>
        /// Required. The Document Id
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is <c>{user agent
        /// name}/{version}</c>.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.         
        /// <example>Fri, 08 Apr 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<AttachmentResponse>> CreateAttachementWithOperationResponseAsync(string ridDB, string ridColl, string ridDoc, AttachmentRaw request, string authorization, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Create a new Collection
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. example - <example>Fri, 08 Apr
        /// 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use
        /// <c>2015-08-06</c>
        /// </param>
        /// <param name='id'>
        /// Required. This is a user settable property. It is the unique name
        /// that identifies the collection
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<Collection>> CreateCollectionWithOperationResponseAsync(string ridDB, string authorization, string xMSDate, string xMSVersion, CustomBodyCollection id, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='contentType'>
        /// Required. For creating a database, the Content-Type header must be
        /// `<c>application/json</c>`.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.  <example>Fri, 08 Apr 2015
        /// 03:52:31 GMT</example>
        /// </param>
        /// <param name='id'>
        /// Required. This is a user settable property. It is the unique name
        /// that identifies the collection
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<Database>> CreateDatabaseWithOperationResponseAsync(string authorization, string contentType, string xMSDate, CustomBodyCollection id, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Create a new Document
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection Id
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. <example>Fri, 08 Apr 2015
        /// 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use
        /// <c>2015-08-06</c>
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<Document>> CreateDocumentWithOperationResponseAsync(string ridDB, string ridColl, CustomBody request, string authorization, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Create a User
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='contentType'>
        /// Required. Optional. For creating a database, the Content-Type
        /// header must be application/json.
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request..
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.          example -
        /// <example>Fri, 08 Apr 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<User>> CreateUserWithOperationResponseAsync(string ridDB, User request, string authorization, string contentType, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete a Collection
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection Id
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is <c>{user agent
        /// name}/{version}</c>.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.           example -
        /// <example>Fri, 08 Apr 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use
        /// <c>2015-08-06</c>
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> DeleteCollectionWithOperationResponseAsync(string ridDB, string ridColl, string authorization, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete a Database
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='contentType'>
        /// Required. Optional. For creating a database, the Content-Type
        /// header must be application/json.
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is <c>{user agent
        /// name}/{version}</c>
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.           
        /// <example>Fri, 08 Apr 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use
        /// <c>2015-08-06</c>
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> DeleteDatabaseWithOperationResponseAsync(string ridDB, string authorization, string contentType, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete a Document
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection Id
        /// </param>
        /// <param name='ridDoc'>
        /// Required. The Document Id
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this
        /// operation.<c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. <example>Fri, 08 Apr 2015
        /// 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> DeleteDocumentWithOperationResponseAsync(string ridDB, string ridColl, string ridDoc, string authorization, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// To delete a permission resource, perform a DELETE operation on that
        /// permission resource
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridPerm'>
        /// Required. The Permission Id
        /// </param>
        /// <param name='ridUser'>
        /// Required. The User Id
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='contentType'>
        /// Required. Optional. For creating a database, the Content-Type
        /// header must be application/json.
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is <c>{user agent
        /// name}/{version}</c>
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. example: <example>Fri, 08 Apr
        /// 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> DeletePermissionWithOperationResponseAsync(string ridDB, string ridPerm, string ridUser, string authorization, string contentType, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete a User
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridUser'>
        /// Required. The User Id
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation. example:
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='contentType'>
        /// Required. Optional. For creating a database, the Content-Type
        /// header must be application/json.
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is <c>{user agent
        /// name}/{version}</c>.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.          example -
        /// <example>Fri, 08 Apr 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> DeleteUserWithOperationResponseAsync(string ridDB, string ridUser, string authorization, string contentType, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Execute a Stored Procedure
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection Id
        /// </param>
        /// <param name='ridProc'>
        /// Required. The Procedure Id
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='contentType'>
        /// Required. Required. The Content-Type header must be
        /// application/json.
        /// </param>
        /// <param name='xMSDocumentdbQueryEnableScan'>
        /// Required.
        /// </param>
        /// <param name='xMSDocumentdbIsquery'>
        /// Required.
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is <c>{user agent
        /// name}/{version}</c>.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.          example - :
        /// <example>Fri, 08 Apr 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<QueryResponseBody>> ExecuteStoredProcedureWithOperationResponseAsync(string ridDB, string ridColl, string ridProc, QueryRequest request, string authorization, string contentType, bool xMSDocumentdbQueryEnableScan, bool xMSDocumentdbIsquery, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get an Attachment from document
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection Id
        /// </param>
        /// <param name='ridDoc'>
        /// Required. The Document Id
        /// </param>
        /// <param name='ridAttch'>
        /// Required. The Attachment Id
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is <c>{user agent
        /// name}/{version}</c>.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.           example -
        /// <example>Fri, 08 Apr 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<AttachmentRaw>> GetAttachementWithOperationResponseAsync(string ridDB, string ridColl, string ridDoc, string ridAttch, string authorization, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get a Collection
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection Id
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is <c>{user agent
        /// name}/{version}</c>.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.  example - <example>Fri, 08 Apr
        /// 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use
        /// <c>2015-08-06</c>
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<Collection>> GetCollectionByIdWithOperationResponseAsync(string ridDB, string ridColl, string authorization, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Retrieve a database resource by Id
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='contentType'>
        /// Required. Optional. For creating a database, the Content-Type
        /// header must be `application/json`.
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is <c>{user agent
        /// name}/{version}</c>.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. <example>Fri, 08 Apr 2015
        /// 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use
        /// <c>2015-08-06</c>
        /// </param>
        /// <param name='xMSGatewayversion'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<Database>> GetDatabaseByIdWithOperationResponseAsync(string ridDB, string authorization, string contentType, string userAgent, string xMSDate, string xMSVersion, string xMSGatewayversion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// List Databases
        /// </summary>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is `<c>>{user agent
        /// name}/{version}</c>`.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.  `Fri, 08 Apr 2015 03:52:31 GMT`
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use
        /// <c>2015-08-06</c>
        /// </param>
        /// <param name='xMSGatewayversion'>
        /// Required. The Microsft Date Gateway version
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<DatabaseCollection>>> GetDatabaseListWithOperationResponseAsync(string authorization, string userAgent, string xMSDate, string xMSVersion, string xMSGatewayversion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get a Document.
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection Id
        /// </param>
        /// <param name='ridDoc'>
        /// Required. The Document Id
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='userAgent'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. <example>Fri, 08 Apr 2015
        /// 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use
        /// <c>2015-08-06</c>
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<Document>> GetDocumentByIdWithOperationResponseAsync(string ridDB, string ridColl, string ridDoc, string authorization, string userAgent, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='databaseaccount'>
        /// Required. The Database Account Name
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation. example:
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='contentType'>
        /// Required. Optional. For creating a database, the Content-Type
        /// header must be application/json.
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. <example>Fri, 08 Apr 2015
        /// 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<Offer>>> GetListOfOffersWithOperationResponseAsync(string databaseaccount, string authorization, string contentType, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get a list of users resource of a particular database
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='contentType'>
        /// Required. Optional. For creating a database, the Content-Type
        /// header must be application/json.
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is <c>{user agent
        /// name}/{version}</c>.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.          example -
        /// <example>Fri, 08 Apr 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<User>>> GetListOfUsersWithOperationResponseAsync(string ridDB, string authorization, string contentType, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='ridOffer'>
        /// Required. The Offer Id
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation. example:
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='contentType'>
        /// Required. Optional. For creating a database, the Content-Type
        /// header must be application/json.
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is <c>{user agent
        /// name}/{version}</c>.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. example: <example>Fri, 08 Apr
        /// 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<Offer>> GetOfferWithOperationResponseAsync(string ridOffer, string authorization, string contentType, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Performing a GET operation on a specific permission resource
        /// retrieves the permission properties, including the token, for the
        /// particular permission. A new resource token is created every time
        /// a GET is invoked on the permission resource. This new token has
        /// the default validity period of one hour, unless it is overridden.
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridUser'>
        /// Required. The User Id
        /// </param>
        /// <param name='ridPerm'>
        /// Required. The Permission Id
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation. example:
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='contentType'>
        /// Required. Optional. For creating a database, the Content-Type
        /// header must be application/json.
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is {user agent name}/{version}.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. example- <example>Fri, 08 Apr
        /// 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<Permission>> GetPermissionWithOperationResponseAsync(string ridDB, string ridUser, string ridPerm, string authorization, string contentType, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get a User
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridUser'>
        /// Required. The User Id
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='contentType'>
        /// Required. Optional. For creating a database, the Content-Type
        /// header must be application/json.
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is <c>{user agent
        /// name}/{version}</c>.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.          example -
        /// <example>Fri, 08 Apr 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<User>> GetUserByIdWithOperationResponseAsync(string ridDB, string ridUser, string authorization, string contentType, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// List Collections
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is <c>{user agent
        /// name}/{version}</c>.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. example - <example>Fri, 08 Apr
        /// 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use
        /// <c>2015-08-06</c>
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<Collection>>> ListCollectionsWithOperationResponseAsync(string ridDB, string authorization, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// List Documents
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection Id
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. <example>Fri, 08 Apr 2015
        /// 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use
        /// <c>2015-08-06</c>
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<Document>>> ListDocumentsWithOperationResponseAsync(string ridDB, string ridColl, string authorization, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection Id
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. <example>Fri, 08 Apr 2015
        /// 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use
        /// <c>2015-08-06</c>
        /// </param>
        /// <param name='contentType'>
        /// Required. Must be set to application/query+json
        /// </param>
        /// <param name='xMSDocumentdbIsquery'>
        /// Required. Required. This property must be set to true
        /// </param>
        /// <param name='xMSMaxItemCount'>
        /// Required. To page through a result set, set this header to the
        /// maximum number for items to be returned back in a single page.
        /// <remarks>Range 1 - 1000 Default value = 100</remarks>
        /// </param>
        /// <param name='xMSContinuation'>
        /// Required. To navigate to the next page of items, set this header to
        /// the continuation token for the next page.
        /// </param>
        /// <param name='xMSDocumentdbQueryEnableScan'>
        /// Required. Use an index scan to process the query if the right index
        /// path of type is not available.
        /// </param>
        /// <param name='xMSSessionToken'>
        /// Required. The session token for the request. Used for session
        /// consistency
        /// </param>
        /// <param name='accept'>
        /// Required. Optional. At the moment, DocumentDB always returns the
        /// response payload in standard JSON format. The client must be able
        /// to accept the response body in standard JSON format
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<QueryResourceResponseBody>> QueryCollectionResourceWithOperationResponseAsync(string ridDB, string ridColl, QueryRequest request, string authorization, string userAgent, string xMSDate, string xMSVersion, string contentType, bool xMSDocumentdbIsquery, string xMSMaxItemCount, string xMSContinuation, bool? xMSDocumentdbQueryEnableScan, string xMSSessionToken, string accept, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection Id
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. <example>Fri, 08 Apr 2015
        /// 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use
        /// <c>2015-08-06</c>
        /// </param>
        /// <param name='contentType'>
        /// Required. Must be set to application/query+json
        /// </param>
        /// <param name='xMSDocumentdbIsquery'>
        /// Required. Required. This property must be set to true
        /// </param>
        /// <param name='xMSMaxItemCount'>
        /// Required. To page through a result set, set this header to the
        /// maximum number for items to be returned back in a single page.
        /// <remarks>Range 1 - 1000 Default value = 100</remarks>
        /// </param>
        /// <param name='xMSContinuation'>
        /// Required. To navigate to the next page of items, set this header to
        /// the continuation token for the next page.
        /// </param>
        /// <param name='xMSDocumentdbQueryEnableScan'>
        /// Required. Use an index scan to process the query if the right index
        /// path of type is not available.
        /// </param>
        /// <param name='xMSSessionToken'>
        /// Required. The session token for the request. Used for session
        /// consistency
        /// </param>
        /// <param name='accept'>
        /// Required. Optional. At the moment, DocumentDB always returns the
        /// response payload in standard JSON format. The client must be able
        /// to accept the response body in standard JSON format
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<QueryResourceResponseBody>> QueryDocumentResourceWithOperationResponseAsync(string ridDB, string ridColl, QueryRequest request, string authorization, string userAgent, string xMSDate, string xMSVersion, string contentType, bool xMSDocumentdbIsquery, string xMSMaxItemCount, string xMSContinuation, bool? xMSDocumentdbQueryEnableScan, string xMSSessionToken, string accept, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='databaseaccount'>
        /// Required. The Database Account Name
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation. example:
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is <c>{user agent
        /// name}/{version}</c>.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. example: <example>Fri, 08 Apr
        /// 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='contentType'>
        /// Required. Required. The Content-Type header must be
        /// application/json.
        /// </param>
        /// <param name='xMSDocumentdbQueryEnableScan'>
        /// Required.
        /// </param>
        /// <param name='xMSDocumentdbIsquery'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<QueryResponseBody>> QueryOfferWithOperationResponseAsync(string databaseaccount, QuerySql request, string authorization, string userAgent, string xMSDate, string xMSVersion, string contentType, bool xMSDocumentdbQueryEnableScan, bool xMSDocumentdbIsquery, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Query a Permission
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridUser'>
        /// Required. The User Id
        /// </param>
        /// <param name='request'>
        /// Required. The Request Body
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='contentType'>
        /// Required. Required. The Content-Type header must be
        /// application/json.
        /// </param>
        /// <param name='xMSDocumentdbQueryEnableScan'>
        /// Required.
        /// </param>
        /// <param name='xMSDocumentdbIsquery'>
        /// Required.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. example - <example>Fri, 08 Apr
        /// 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<QueryResponseBody>> QueryPermissionWithOperationResponseAsync(string ridDB, string ridUser, QueryRequest request, string authorization, string contentType, bool xMSDocumentdbQueryEnableScan, bool xMSDocumentdbIsquery, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Query a Trigger
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection Id
        /// </param>
        /// <param name='contentType'>
        /// Required. Required. The Content-Type header must be
        /// application/json.
        /// </param>
        /// <param name='xMSDocumentdbQueryEnableScan'>
        /// Required.
        /// </param>
        /// <param name='xMSDocumentdbIsquery'>
        /// Required.
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is <c>{user agent
        /// name}/{version}</c>.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.       example - <example>Fri,
        /// 08 Apr 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<QueryResponseBody>> QueryTriggerWithOperationResponseAsync(string ridDB, string ridColl, string contentType, bool xMSDocumentdbQueryEnableScan, bool xMSDocumentdbIsquery, QueryRequest request, string authorization, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Query a UDF
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection Id
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='contentType'>
        /// Required. Required. The Content-Type header must be
        /// application/json.
        /// </param>
        /// <param name='xMSDocumentdbQueryEnableScan'>
        /// Required.
        /// </param>
        /// <param name='xMSDocumentdbIsquery'>
        /// Required.
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is 
        /// <c>{user agent name}/{version}</c>
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. example: <example>Fri, 08 Apr
        /// 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<QueryResponseBody>> QueryUdfWithOperationResponseAsync(string ridDB, string ridColl, QueryRequest request, string authorization, string contentType, bool xMSDocumentdbQueryEnableScan, bool xMSDocumentdbIsquery, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Register a Stored Procedure
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection Id
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is <c>{user agent
        /// name}/{version}</c>.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.         -
        /// <example>Fri, 08 Apr 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<StoredProcedure>> RegisterStoredProcedureWithOperationResponseAsync(string ridDB, string ridColl, QueryRequest request, string authorization, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Replace a Document
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection Id
        /// </param>
        /// <param name='ridDoc'>
        /// Required. The Document Id
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. <example>Fri, 08 Apr 2015
        /// 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='request'>
        /// Optional.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<Document>> ReplaceDocumentWithOperationResponseAsync(string ridDB, string ridColl, string ridDoc, string authorization, string userAgent, string xMSDate, string xMSVersion, Document request = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='ridOffer'>
        /// Required. The Offer Id
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='contentType'>
        /// Required. Optional. For creating a database, the Content-Type
        /// header must be application/json.
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is <c>{user agent
        /// name}/{version}</c>.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. example: <example>Fri, 08 Apr
        /// 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<Offer>> ReplaceOfferWithOperationResponseAsync(string ridOffer, ReplaceOffer request, string authorization, string contentType, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Replaces the entire user Permission.
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridUser'>
        /// Required. The User Id
        /// </param>
        /// <param name='ridPerm'>
        /// Required. The Permission Id
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='contentType'>
        /// Required. Optional. For creating a database, the Content-Type
        /// header must be application/json.
        /// </param>
        /// <param name='userAgent'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. example: <example>Fri, 08 Apr
        /// 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. example- <example>Fri, 08 Apr
        /// 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<Permission>> ReplacePermissionWithOperationResponseAsync(string ridDB, string ridUser, string ridPerm, Permission request, string authorization, string contentType, string userAgent, string xMSVersion, string xMSDate, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Replace a User
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridUser'>
        /// Required. The User Id
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation.
        /// <c>type={typeoftoken}%26ver={tokenversion}%26sig={hashsignature}</c>
        /// </param>
        /// <param name='contentType'>
        /// Required. Optional. For creating a database, the Content-Type
        /// header must be application/json.
        /// </param>
        /// <param name='userAgent'>
        /// Required. Optional. The string of client user agent performing the
        /// request. The recommended format is <c>{user agent
        /// name}/{version}</c>.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.          example: -
        /// <example>Fri, 08 Apr 2015 03:52:31 GMT</example>
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<User>> ReplaceUserWithOperationResponseAsync(string ridDB, string ridUser, User request, string authorization, string contentType, string userAgent, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));
    }
}
