// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using Newtonsoft.Json.Linq;

namespace DocDbCollectionAPI.Models
{
    public class CustomBody
    {

        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <param name="outputObject">todo: describe outputObject parameter on SerializeJson</param>
        /// <returns>
        /// Returns the json model for the type CustomBody
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (Custom != null)
            {
                outputObject["custom"] = Custom;
            }
            return outputObject;
        }

        /// <summary>
        /// Optional. A JSON array of parameters specified as name value pairs.
        /// </summary>
        public string Custom { get; set; }
    }
}
