// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;

namespace DocumentDBRestApi.Models
{
    /// <summary>
    /// 
    /// </summary>
    public class Attachment
    {
        /// <summary>
        /// Required. This is a user settable property. It specifies the
        /// content type of the attachment. .
        /// </summary>
        public string ContentType { get; set; }

        /// <summary>
        /// Required. This is a user settable property. It is the unique name
        /// that identifies the attachment, i.e. no two attachments share the
        /// same id. The id must not exceed 255 characters.
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// Required. This is the URL link or file path where the attachment
        /// resides.
        /// </summary>
        public string Media { get; set; }

        /// <summary>
        /// Initializes a new instance of the Attachment class.
        /// </summary>
        public Attachment()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the Attachment class with required
        /// arguments.
        /// </summary>
        public Attachment(string id, string contentType, string media)
            : this()
        {
            if (id == null)
            {
                throw new ArgumentNullException(nameof(id));
            }
            if (contentType == null)
            {
                throw new ArgumentNullException(nameof(contentType));
            }
            if (media == null)
            {
                throw new ArgumentNullException(nameof(media));
            }
            Id = id;
            ContentType = contentType;
            Media = media;
        }
    }
}
