// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using Newtonsoft.Json.Linq;

namespace DocumentDBRestApi.Models
{
    /// <summary>
    /// 
    /// </summary>
    public class CustomBodyCollection
    {
        /// <summary>
        /// Required. A JSON array of parameters specified as name value pairs.
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// Initializes a new instance of the CustomBodyCollection class.
        /// </summary>
        public CustomBodyCollection()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the CustomBodyCollection class with
        /// required arguments.
        /// </summary>
        public CustomBodyCollection(string id)
            : this()
        {
            if (id == null)
            {
                throw new ArgumentNullException(nameof(id));
            }
            Id = id;
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type CustomBodyCollection
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (Id == null)
            {
                throw new ArgumentNullException(nameof(Id));
            }
            if (Id != null)
            {
                outputObject["id"] = Id;
            }
            return outputObject;
        }
    }
}
