// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace DocumentDBRestApi.Models
{
    /// <summary>
    /// 
    /// </summary>
    public static class DocumentCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Document> DeserializeJson(JToken inputObject)
        {
            IList<Document> deserializedObject = new List<Document>();
            foreach (var iListValue in ((JArray)inputObject))
            {
                var document = new Document();
                document.DeserializeJson(iListValue);
                deserializedObject.Add(document);
            }
            return deserializedObject;
        }
    }
}
