// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using Microsoft.WindowsAzure.Common.Internals;
using Newtonsoft.Json.Linq;

namespace DocumentDBRestApi.Models
{
    /// <summary>
    /// 
    /// </summary>
    public class QueryRequest
    {
        /// <summary>
        /// Required. A JSON array of parameters specified as name value pairs.
        /// The parameter array can contain from zero to many parameters.Each
        /// parameter must have the following values:name: the name of the
        /// parameter. Parameter names must be valid string literals and begin
        /// with ‘@’.value: the value of the parameter. Can be any valid JSON
        /// value (string, number, object, array, Boolean or null).
        /// </summary>
        public IList<string> Parameters { get; set; }

        /// <summary>
        /// Required. The SQL query string for the query
        /// </summary>
        public string QueryString { get; set; }

        /// <summary>
        /// Initializes a new instance of the QueryRequest class.
        /// </summary>
        public QueryRequest()
        {
            Parameters = new LazyList<string>();
        }
        
        /// <summary>
        /// Initializes a new instance of the QueryRequest class with required
        /// arguments.
        /// </summary>
        public QueryRequest(string queryString, IList<string> parameters)
            : this()
        {
            if (queryString == null)
            {
                throw new ArgumentNullException(nameof(queryString));
            }
            if (parameters == null)
            {
                throw new ArgumentNullException(nameof(parameters));
            }
            QueryString = queryString;
            Parameters = parameters;
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type QueryRequest
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            var parameters = Parameters as ILazyCollection;
            if (parameters != null && parameters.IsInitialized == false || Parameters == null)
            {
                throw new ArgumentNullException(nameof(Parameters));
            }
            if (QueryString == null)
            {
                throw new ArgumentNullException(nameof(QueryString));
            }
            var collection = (ILazyCollection) Parameters;
            if (collection != null && !collection.IsInitialized)
            {
                var parametersSequence = new JArray();
                outputObject["parameters"] = parametersSequence;
                foreach (var parametersItem in Parameters)
                {
                    if (parametersItem != null)
                    {
                        parametersSequence.Add(parametersItem);
                    }
                }
            }
            if (QueryString != null)
            {
                outputObject["QueryString"] = QueryString;
            }
            return outputObject;
        }
    }
}
