// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using Newtonsoft.Json.Linq;

namespace DocumentDBRestApi.Models
{
    /// <summary>
    /// 
    /// </summary>
    public class ReplaceOffer
    {
        /// <summary>
        ///     Required. This is the resource id of the offer.
        /// </summary>
        public string Rid { get; set; }

        /// <summary>
        ///     Required. The id for the offer resource. It has the same value as
        ///     the _rid for the offer.
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        ///     Required. This must be the resource id of the collection associated
        ///     to the offer resource. It cannot be changed. The resource id must
        ///     match collection _rid in the resource property.
        /// </summary>
        public string OfferResourceId { get; set; }

        /// <summary>
        ///     Required. This is a user settable property. The valid values are
        ///     S1, S2 and S3. The value must be capitalized
        /// </summary>
        public string OfferType { get; set; }

        /// <summary>
        ///     Required. This must be the self-link of the collection associated
        ///     to the offer resource
        /// </summary>
        public string Resource { get; set; }

        /// <summary>
        ///     Serialize the object
        /// </summary>
        /// <returns>
        ///     Returns the json model for the type ReplaceOffer
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (Rid == null)
            {
                throw new ArgumentNullException(nameof(Rid));
            }
            if (Id == null)
            {
                throw new ArgumentNullException(nameof(Id));
            }
            if (OfferResourceId == null)
            {
                throw new ArgumentNullException(nameof(OfferResourceId));
            }
            if (OfferType == null)
            {
                throw new ArgumentNullException(nameof(OfferType));
            }
            if (Resource == null)
            {
                throw new ArgumentNullException(nameof(Resource));
            }
            if (Rid != null)
            {
                outputObject["_rid"] = Rid;
            }
            if (Id != null)
            {
                outputObject["id"] = Id;
            }
            if (OfferResourceId != null)
            {
                outputObject["offerResourceId"] = OfferResourceId;
            }
            if (OfferType != null)
            {
                outputObject["offerType"] = OfferType;
            }
            if (Resource != null)
            {
                outputObject["resource"] = Resource;
            }
            return outputObject;
        }
    }
}