// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;

namespace DocumentDBRestApi.Models
{
    /// <summary>
    /// 
    /// </summary>
    public class Udf
    {
        /// <summary>
        /// Optional.
        /// </summary>
        public string Etag { get; set; }

        /// <summary>
        /// Optional.
        /// </summary>
        public string Rid { get; set; }

        /// <summary>
        /// Optional.
        /// </summary>
        public string Self { get; set; }

        /// <summary>
        /// Optional.
        /// </summary>
        public string Ts { get; set; }

        /// <summary>
        /// Required. This is a user settable property. This is the body of the
        /// UDF
        /// </summary>
        public string Body { get; set; }

        /// <summary>
        /// Required. This is a user settable property. It is a unique name to
        /// identify the UDF. The id must not exceed 255 characters.
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// Initializes a new instance of the Udf class.
        /// </summary>
        public Udf()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the Udf class with required arguments.
        /// </summary>
        public Udf(string id, string body)
            : this()
        {
            if (id == null)
            {
                throw new ArgumentNullException(nameof(id));
            }
            if (body == null)
            {
                throw new ArgumentNullException(nameof(body));
            }
            Id = id;
            Body = body;
        }
    }
}
