// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using DocDbCollectionAPI.Models;
using Microsoft.Rest;

namespace DocDbCollectionAPI
{
    public interface IDocDbCollectionApiClient : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri
        {
            get; set; 
        }
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        ServiceClientCredentials Credentials
        {
            get; set; 
        }
        
        /// <summary>
        /// Create an Attachment
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection ID
        /// </param>
        /// <param name='ridDoc'>
        /// Required. The Document ID
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.           example - Fri, 08 Apr
        /// 2015 03:52:31 GMT
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<AttachmentResponse>> CreateAttachementWithOperationResponseAsync(string ridDB, string ridColl, string ridDoc, Attachment request, string authorization, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));
        
        /// <summary>
        /// Create a new Document
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection ID
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<Document>> CreateDocumentWithOperationResponseAsync(string ridDB, string ridColl, CustomBody request, string authorization, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));
        
        /// <summary>
        /// Delete a Document
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection ID
        /// </param>
        /// <param name='ridDoc'>
        /// Required. The Document ID
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> DeleteDocumentWithOperationResponseAsync(string ridDB, string ridColl, string ridDoc, string authorization, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));
        
        /// <summary>
        /// Execute a Stored Procedure
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection ID
        /// </param>
        /// <param name='ridProc'>
        /// Required. The Procedure ID
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation
        /// </param>
        /// <param name='contentType'>
        /// Required. Required. The Content-Type header must be
        /// application/json.
        /// </param>
        /// <param name='xMSDocumentdbQueryEnableScan'>
        /// Required.
        /// </param>
        /// <param name='xMSDocumentdbIsquery'>
        /// Required.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.          example - : Fri, 08
        /// Apr 2015 03:52:31 GMT
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<QueryResponseBody>> ExecuteStoredProcedureWithOperationResponseAsync(string ridDB, string ridColl, string ridProc, QueryRequest request, string authorization, string contentType, bool xMSDocumentdbQueryEnableScan, bool xMSDocumentdbIsquery, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));
        
        /// <summary>
        /// Get an Attachment from document
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection ID
        /// </param>
        /// <param name='ridDoc'>
        /// Required. The Document ID
        /// </param>
        /// <param name='ridAttch'>
        /// Required. The Attachment ID
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.           example - Fri, 08 Apr
        /// 2015 03:52:31 GMT
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<AttachmentRaw>> GetAttachementWithOperationResponseAsync(string ridDB, string ridColl, string ridDoc, string ridAttch, string authorization, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));
        
        /// <summary>
        /// Get a Document.
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection ID
        /// </param>
        /// <param name='ridDoc'>
        /// Required. The Document ID
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<Document>> GetDocumentByIdWithOperationResponseAsync(string ridDB, string ridColl, string ridDoc, string authorization, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));
        
        /// <summary>
        /// List Documents
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection ID
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<Document>>> ListDocumentsWithOperationResponseAsync(string ridDB, string ridColl, string authorization, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));
        
        /// <summary>
        /// Get a list of Stored Procedures for the Collection
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection ID
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<StoredProcedure>>> ListStoredProceduresWithOperationResponseAsync(string ridDB, string ridColl, string authorization, CancellationToken cancellationToken = default(CancellationToken));
        
        /// <summary>
        /// Perform a document query
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection ID
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<Document>>> QueryDocumentsWithOperationResponseAsync(string ridDB, string ridColl, string authorization, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));
        
        /// <summary>
        /// Query a Trigger
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection ID
        /// </param>
        /// <param name='contentType'>
        /// Required. Required. The Content-Type header must be
        /// application/json.
        /// </param>
        /// <param name='xMSDocumentdbQueryEnableScan'>
        /// Required.
        /// </param>
        /// <param name='xMSDocumentdbIsquery'>
        /// Required.
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.       example - Fri, 08 Apr
        /// 2015 03:52:31 GMT
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<QueryResponseBody>> QueryTriggerWithOperationResponseAsync(string ridDB, string ridColl, string contentType, bool xMSDocumentdbQueryEnableScan, bool xMSDocumentdbIsquery, QueryRequest request, string authorization, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));
        
        /// <summary>
        /// Query a UDF
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection ID
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation
        /// </param>
        /// <param name='contentType'>
        /// Required. Required. The Content-Type header must be
        /// application/json.
        /// </param>
        /// <param name='xMSDocumentdbQueryEnableScan'>
        /// Required.
        /// </param>
        /// <param name='xMSDocumentdbIsquery'>
        /// Required.
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format. example: Fri, 08 Apr 2015
        /// 03:52:31 GMT
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<QueryResponseBody>> QueryUdfWithOperationResponseAsync(string ridDB, string ridColl, QueryRequest request, string authorization, string contentType, bool xMSDocumentdbQueryEnableScan, bool xMSDocumentdbIsquery, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));
        
        /// <summary>
        /// Register/ Create a Stored Procedure
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection ID
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.          example - Fri, 08 Apr
        /// 2015 03:52:31 GMT
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<StoredProcedure>> RegisterStoredProcedureWithOperationResponseAsync(string ridDB, string ridColl, QueryRequest request, string authorization, string xMSDate, string xMSVersion, CancellationToken cancellationToken = default(CancellationToken));
        
        /// <summary>
        /// Replace a Document
        /// </summary>
        /// <param name='ridDB'>
        /// Required. The Database Id
        /// </param>
        /// <param name='ridColl'>
        /// Required. The Collection ID
        /// </param>
        /// <param name='ridDoc'>
        /// Required. The Document ID
        /// </param>
        /// <param name='authorization'>
        /// Required. The authentication type and signature token. Both master
        /// key and resource tokens are allowed for this operation
        /// </param>
        /// <param name='xMSDate'>
        /// Required. The date of the request The date is expressed in
        /// Coordinated Universal Time format.
        /// </param>
        /// <param name='xMSVersion'>
        /// Required. The version of DocumentDB REST service. The latest
        /// version is used when the header is not provided use 2015-08-06
        /// </param>
        /// <param name='request'>
        /// Optional.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<Document>> ReplaceDocumentWithOperationResponseAsync(string ridDB, string ridColl, string ridDoc, string authorization, string xMSDate, string xMSVersion, Document request = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
