// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace DocumentDBRestAPIClient.Models
{
    public static class DatabaseCollectionCollection
    {
        /// <summary>
        ///     Deserialize the object
        /// </summary>
        public static IList<DatabaseCollection> DeserializeJson(JToken inputObject)
        {
            IList<DatabaseCollection> deserializedObject = new List<DatabaseCollection>();
            foreach (var iListValue in (JArray) inputObject)
            {
                var databaseCollection = new DatabaseCollection();
                databaseCollection.DeserializeJson(iListValue);
                deserializedObject.Add(databaseCollection);
            }
            return deserializedObject;
        }
    }
}