// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using Newtonsoft.Json.Linq;

namespace DocumentDBRestAPIClient.Models
{
    public class Offer
    {
        /// <summary>
        ///     Initializes a new instance of the Offer class.
        /// </summary>
        public Offer()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the Offer class with required
        ///     arguments.
        /// </summary>
        public Offer(string offerType, string resource, string offerResourceId)
            : this()
        {
            if (offerType == null)
            {
                throw new ArgumentNullException(nameof(offerType));
            }
            if (resource == null)
            {
                throw new ArgumentNullException(nameof(resource));
            }
            if (offerResourceId == null)
            {
                throw new ArgumentNullException(nameof(offerResourceId));
            }
            OfferType = offerType;
            Resource = resource;
            OfferResourceId = offerResourceId;
        }

        /// <summary>
        ///     Optional. This is a system generated property that specifies the
        ///     resource etag required for optimistic concurrency control.
        /// </summary>
        public string Etag { get; set; }

        /// <summary>
        ///     Optional. This is a system generated property. The resource Id
        ///     (_rid) is a unique identifier that is also hierarchical per the
        ///     resource stack on the resource model. It is used internally for
        ///     placement and navigation of the offer
        /// </summary>
        public string Rid { get; set; }

        /// <summary>
        ///     Optional. This is a system generated property. It is the unique
        ///     addressable URI for the resource.
        /// </summary>
        public string Self { get; set; }

        /// <summary>
        ///     Optional. This is a system generated property. It specifies the
        ///     last updated timestamp of the resource. The value is a timestamp.
        /// </summary>
        public string Ts { get; set; }

        /// <summary>
        ///     Optional. This is a system generated property. The id for the offer
        ///     resource is automatically generated when it is created. It has the
        ///     same value as the _rid for the offer.
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        ///     Required. During creation of a collection, this property is
        ///     automatically associated to the resource id, i.e. _rid of
        ///     collection associated to the offer resource. The resource id must
        ///     match collection _rid in the resource property. In the example
        ///     above, the _rid for the collection is pLJdAOlEdgA=.
        /// </summary>
        public string OfferResourceId { get; set; }

        /// <summary>
        ///     Required. This is a user settable property. The valid values are
        ///     S1, S2 and S3. The value must be capitalized. For more information
        ///     on performance levels, please see DocumentDB performance levels.
        /// </summary>
        public string OfferType { get; set; }

        /// <summary>
        ///     Required. . During creation of a collection, this property is
        ///     automatically associated to the self link of collection associated
        ///     to the offer resource, i.e. dbs/pLJdAA==/colls/pLJdAOlEdgA=/.
        /// </summary>
        public string Resource { get; set; }

        /// <summary>
        ///     Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                var etagValue = inputObject["_etag"];
                if (etagValue != null && etagValue.Type != JTokenType.Null)
                {
                    Etag = (string) etagValue;
                }
                var ridValue = inputObject["_rid"];
                if (ridValue != null && ridValue.Type != JTokenType.Null)
                {
                    Rid = (string) ridValue;
                }
                var selfValue = inputObject["_self"];
                if (selfValue != null && selfValue.Type != JTokenType.Null)
                {
                    Self = (string) selfValue;
                }
                var tsValue = inputObject["_ts"];
                if (tsValue != null && tsValue.Type != JTokenType.Null)
                {
                    Ts = (string) tsValue;
                }
                var idValue = inputObject["id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    Id = (string) idValue;
                }
                var offerResourceIdValue = inputObject["offerResourceId"];
                if (offerResourceIdValue != null && offerResourceIdValue.Type != JTokenType.Null)
                {
                    OfferResourceId = (string) offerResourceIdValue;
                }
                var offerTypeValue = inputObject["offerType"];
                if (offerTypeValue != null && offerTypeValue.Type != JTokenType.Null)
                {
                    OfferType = (string) offerTypeValue;
                }
                var resourceValue = inputObject["resource"];
                if (resourceValue != null && resourceValue.Type != JTokenType.Null)
                {
                    Resource = (string) resourceValue;
                }
            }
        }
    }
}